-------------------------------------------------------------------------------
--  This file is part of the "Lua LOVE Basic"
--
--  @license   The MIT License (MIT) Included in this distribution
--  @author    Zaher Dirkey <zaherdirkey at yahoo dot com>
-------------------------------------------------------------------------------
--USAGE:
--In Windows, Put "basic" folder in the same folder of lua.exe
--Or add to the environments LUA_PATH=!\?.lua;!\?\init.lua;d:\home\lua\lib\?.lua
--In linux add it in ~/.profile or ~/.bashrc
-------------------------------------------------------------------------------
require("basic.utils")